// <auto-generated />
using Hazelnut.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hazelnut.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520040158_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Hazelnut.Models.ToiletPaper", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = -1,
                            Description = "_",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 500g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "500g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -2,
                            Description = "_",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 600g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "600g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -3,
                            Description = "_",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 700g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "700g 2&3 Lớp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
