// <auto-generated />
using Hazelnut.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hazelnut.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521011021_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Hazelnut.Models.SmallToiletPaper", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("SmallToiletPapers");

                    b.HasData(
                        new
                        {
                            ProductId = -4,
                            Description = "_",
                            ImagePath = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f.jpg",
                            ImagePathLarge = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f.jpg 666w",
                            ImagePathMedium = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f-600x338.jpg 600w",
                            Name = "Giấy Vệ Sinh Tesla 10 Cuộn 3 Lớp",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "10 cuộn 3 lớp có lõi và không lõi",
                            Weight = "800g/túi"
                        },
                        new
                        {
                            ProductId = -5,
                            Description = "_",
                            ImagePath = "images/Picture11.png",
                            ImagePathLarge = "images/Picture11.png",
                            Name = "Giấy vệ sinh Posy 10 cuộn 3 lớp có lõi và không lõi",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "_",
                            Weight = "_"
                        });
                });

            modelBuilder.Entity("Hazelnut.Models.ToiletPaper", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("ToiletPapers");

                    b.HasData(
                        new
                        {
                            ProductId = -1,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 500g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "500g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -2,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 600g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "600g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -3,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 700g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "700g 2&3 Lớp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
