// <auto-generated />
using Hazelnut.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hazelnut.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Hazelnut.Models.Napkin", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Napkins");

                    b.HasData(
                        new
                        {
                            ProductId = -6,
                            Description = "_",
                            ImagePath = "images/Picture16.png",
                            ImagePathLarge = "images/Picture16.png 349w",
                            ImagePathSmall = "images/Picture16-100x100.png 100w",
                            Name = "Giấy Lụa Rút Posy 120 Tờ 3 lớp Cao Cấp",
                            Origin = "Posy Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "198mm × 200 mm",
                            Weight = "180 Tờ 3 lớp"
                        },
                        new
                        {
                            ProductId = -7,
                            Description = "_",
                            ImagePath = "images/Picture15.png",
                            ImagePathLarge = "images/Picture15.png",
                            Name = "Giấy Lụa Rút Cata",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "200mm x 185mm",
                            Weight = "280 tờ/ túi x 2 lớp"
                        });
                });

            modelBuilder.Entity("Hazelnut.Models.PaperContainer", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("PaperContainers");

                    b.HasData(
                        new
                        {
                            ProductId = -10,
                            Description = "_",
                            ImagePath = "images/Picture10.png",
                            ImagePathLarge = "images/Picture10.png",
                            Name = "Hộp Đựng Giấy Lau Tay Nhựa",
                            Origin = "Posy Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "_",
                            Weight = "_"
                        },
                        new
                        {
                            ProductId = -11,
                            Description = "_",
                            ImagePath = "images/z5270723986943_6e8a877ec9d8f31c134b0c0d28e49651.jpg",
                            ImagePathLarge = "images/z5270723986943_6e8a877ec9d8f31c134b0c0d28e49651.jpg",
                            Name = "Hộp Đựng Giấy Lau Tay Inox",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "Inox 304 Cao Cấp",
                            Weight = "_"
                        });
                });

            modelBuilder.Entity("Hazelnut.Models.PaperHandkerchiefs", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("PaperHandkerchiefs");

                    b.HasData(
                        new
                        {
                            ProductId = -8,
                            Description = "_",
                            ImagePath = "images/Picture7.png",
                            ImagePathLarge = "images/Picture7.png",
                            Name = "Giấy Lau Tay Đa Năng Posy",
                            Origin = "Posy Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "190mm x 220mm",
                            Weight = "100 Tờ 2 Lớp Gấp 2"
                        },
                        new
                        {
                            ProductId = -9,
                            Description = "_",
                            ImagePath = "images/Picture6.png",
                            ImagePathLarge = "images/Picture6.png",
                            Name = "Giấy Lụa Rút Cata",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "190mm x 220mm",
                            Weight = "100 Tờ 2 Lớp"
                        });
                });

            modelBuilder.Entity("Hazelnut.Models.SmallToiletPaper", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("SmallToiletPapers");

                    b.HasData(
                        new
                        {
                            ProductId = -4,
                            Description = "_",
                            ImagePath = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f.jpg",
                            ImagePathLarge = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f.jpg 666w",
                            ImagePathMedium = "images/z5255371706902_f30db0cd5c7b7752529b437b38b1194f-600x338.jpg 600w",
                            Name = "Giấy Vệ Sinh Tesla 10 Cuộn 3 Lớp",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "10 cuộn 3 lớp có lõi và không lõi",
                            Weight = "800g/túi"
                        },
                        new
                        {
                            ProductId = -5,
                            Description = "_",
                            ImagePath = "images/Picture11.png",
                            ImagePathLarge = "images/Picture11.png",
                            Name = "Giấy vệ sinh Posy 10 cuộn 3 lớp có lõi và không lõi",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "_",
                            Weight = "_"
                        });
                });

            modelBuilder.Entity("Hazelnut.Models.ToiletPaper", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("ToiletPapers");

                    b.HasData(
                        new
                        {
                            ProductId = -1,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 500g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "500g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -2,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 600g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "600g 2&3 Lớp"
                        },
                        new
                        {
                            ProductId = -3,
                            Description = "_",
                            ImagePath = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg",
                            ImagePathLarge = "images/z5255387897448_58d446087449c96b41a44c4db8516e17.jpg 500w",
                            ImagePathMedium = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-400x400.jpg 400w",
                            ImagePathSmall = "images/z5255387897448_58d446087449c96b41a44c4db8516e17-100x100.jpg 100w",
                            Name = "Giấy Vệ Sinh Cuộn Lớn 700g MC",
                            Origin = "Việt Nam",
                            Price = "200k/kg",
                            Producer = "Thế Giới Giấy",
                            Size = "100% Bột giấy nguyên sinh cao cấp",
                            Weight = "700g 2&3 Lớp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
